CREATE TABLE IF NOT EXISTS public.csen_mismatches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mismatch_type varchar(50) NOT NULL, -- 'MISSING_IN_CSEN' o 'MISSING_IN_DB'
    nominativo varchar(255) NOT NULL,
    codice_fiscale varchar(16),
    tessera_csen varchar(50),
    dettagli jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS
ALTER TABLE public.csen_mismatches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for authenticated users" ON public.csen_mismatches
    AS PERMISSIVE FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Enable all access for service role" ON public.csen_mismatches
    AS PERMISSIVE FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);
